name: Generate Swagger Docs

on:
  push:
  workflow_dispatch:

jobs:
  generate-swagger:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Generate Swagger spec
        run: npm run generate:swagger

      - name: Start Express app in background
        run: |
          nohup npm run start &> server.log &
          sleep 5

      - name: Check Swagger UI is live
        run: |
          curl -sSf http://localhost:3000/docs > /dev/null && echo "Swagger UI is up" || (echo "Swagger failed to respond"; cat server.log; exit 1)
